# Spectral linting rules for OpenAPI
extends: ["@stoplight/spectral:oas"]

rules:
  # Require operation summaries
  operation-summary: error
  
  # Require operation descriptions
  operation-description: warn
  
  # Require examples in schemas
  oas3-schema-examples: warn
  
  # Custom rules
  tag-description:
    description: "Tags must have descriptions"
    given: "$.tags[*]"
    severity: warn
    then:
      field: description
      function: truthy
      
  no-empty-servers:
    description: "Servers array cannot be empty"
    given: "$.servers"
    severity: error
    then:
      function: length
      functionOptions:
        min: 1
