openapi: 3.0.3
info:
  title: XStr.me API
  description: |
    OpenAPI specification for XStr.me services.

    This API provides endpoints for managing and accessing XStr.me functionality.
  version: '0.0.1-alpha'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.xstr.me/v1
    description: Production server
  - url: https://staging-api.xstr.me/v1
    description: Staging server
  - url: http://localhost:8080/v1
    description: Local development server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: API is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /version:
    get:
      summary: Get API version
      description: Returns the current version of the API
      operationId: getVersion
      tags:
        - Info
      responses:
        '200':
          description: API version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          description: Health status of the API
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the health check
        version:
          type: string
          description: API version
        uptime:
          type: string
          description: API uptime duration
          example: '2d 5h 30m'
      example:
        status: healthy
        timestamp: '2025-05-27T10:30:00Z'
        version: '0.0.1-alpha'
        uptime: '2d 5h 30m'

    VersionResponse:
      type: object
      required:
        - version
        - build
      properties:
        version:
          type: string
          description: API version
        build:
          type: string
          description: Build number or commit hash
        timestamp:
          type: string
          format: date-time
          description: Build timestamp
      example:
        version: '0.0.1-alpha'
        build: 'abc123def'
        timestamp: '2025-05-27T08:00:00Z'

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
      example:
        error: 'SERVICE_UNAVAILABLE'
        message: 'The service is temporarily unavailable'
        timestamp: '2025-05-27T10:30:00Z'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

security:
  - BearerAuth: []

tags:
  - name: Health
    description: Health check operations
  - name: Info
    description: API information operations
