/* tslint:disable */
/* eslint-disable */
/**
 * XStr.me API
 * OpenAPI specification for XStr.me services.  This API provides endpoints for managing and accessing XStr.me functionality. 
 *
 * The version of the OpenAPI document: 0.0.1-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * Health status of the API
     * @type {string}
     * @memberof HealthResponse
     */
    'status': HealthResponseStatusEnum;
    /**
     * Timestamp of the health check
     * @type {Date}
     * @memberof HealthResponse
     */
    'timestamp': Date;
    /**
     * API version
     * @type {string}
     * @memberof HealthResponse
     */
    'version'?: string;
    /**
     * API uptime duration
     * @type {string}
     * @memberof HealthResponse
     */
    'uptime'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum HealthResponseStatusEnum {
    HEALTHY = 'healthy',
    UNHEALTHY = 'unhealthy'
}


