/* tslint:disable */
/* eslint-disable */
/**
 * XStr.me API
 * OpenAPI specification for XStr.me services.  This API provides endpoints for managing and accessing XStr.me functionality. 
 *
 * The version of the OpenAPI document: 0.0.1-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VersionResponse
 */
export interface VersionResponse {
    /**
     * API version
     * @type {string}
     * @memberof VersionResponse
     */
    'version': string;
    /**
     * Build number or commit hash
     * @type {string}
     * @memberof VersionResponse
     */
    'build': string;
    /**
     * Build timestamp
     * @type {string}
     * @memberof VersionResponse
     */
    'timestamp'?: string;
}

