name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: npm ci
      
    - name: Validate OpenAPI spec
      run: npm run validate
      
    - name: Lint OpenAPI spec
      run: npm run lint
      
    - name: Generate documentation
      run: |
        mkdir -p docs
        npm run generate-docs
        
    - name: Upload docs preview
      uses: actions/upload-artifact@v3
      with:
        name: docs-preview
        path: docs/
