name: Development Quality Checks

on:
  push:
    branches: ['feat/**', 'fix/**', 'chore/**']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-quality:
    name: Code Quality & Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Validate commit messages
        uses: wagroid/commitlint-github-action@v5
        if: github.event_name == 'pull_request'

  workspace-health:
    name: Workspace Health Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install dependencies
        run: npm ci

      - name: Install workspace dependencies
        run: npm run workspace:install

      - name: Run development utilities validation
        run: npm run dev:utils validate

      - name: Check workspace synchronization
        run: npm run version:sync

      - name: Validate Maven integration
        run: npm run maven:validate

  pre-commit-simulation:
    name: Simulate Pre-commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Simulate lint-staged
        run: npx lint-staged --diff="origin/${{ github.base_ref }}...HEAD"
        if: github.event_name == 'pull_request'
